-- VibeLegal Demo Data
-- This file contains sample data for demonstration purposes

-- Insert demo users
INSERT INTO users (email, password_hash, subscription_tier, contracts_used_this_month) VALUES 
('demo@vibelegal.com', '$2a$10$rOvHPGkwQGKqvzjjjjjjjOeKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK', 'basic', 3),
('premium@vibelegal.com', '$2a$10$rOvHPGkwQGKqvzjjjjjjjOeKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK', 'premium', 15),
('lawyer@lawfirm.com', '$2a$10$rOvHPGkwQGKqvzjjjjjjjOeKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK', 'basic', 8);

-- Insert demo contracts
INSERT INTO contracts (user_id, contract_type, title, content, created_at) VALUES 
(1, 'Employment Agreement', 'Software Developer Employment - TechCorp & John Smith', 
'EMPLOYMENT AGREEMENT

This Employment Agreement ("Agreement") is entered into on [DATE], between TechCorp Inc., a Delaware corporation ("Company"), and John Smith ("Employee").

1. POSITION AND DUTIES
Employee shall serve as Software Developer and shall perform such duties as are customarily associated with such position.

2. COMPENSATION
Employee shall receive an annual salary of $85,000, payable in accordance with Company''s standard payroll practices.

3. BENEFITS
Employee shall be entitled to participate in all benefit programs generally available to Company employees.

4. TERM
This Agreement shall commence on [START DATE] and shall continue until terminated in accordance with the provisions herein.

5. TERMINATION
Either party may terminate this Agreement with two (2) weeks written notice.

6. CONFIDENTIALITY
Employee agrees to maintain the confidentiality of all proprietary information of the Company.

7. GOVERNING LAW
This Agreement shall be governed by the laws of the State of California.

IN WITNESS WHEREOF, the parties have executed this Agreement as of the date first written above.

COMPANY:                           EMPLOYEE:
TechCorp Inc.                      John Smith

By: _________________             _________________
Name: [CEO Name]                   John Smith
Title: Chief Executive Officer

LEGAL DISCLAIMER: This document is generated by AI and should be reviewed by a qualified attorney before use. This does not constitute legal advice.',
NOW() - INTERVAL ''2 days''),

(1, 'NDA', 'Non-Disclosure Agreement - TechCorp & Consulting Firm', 
'NON-DISCLOSURE AGREEMENT

This Non-Disclosure Agreement ("Agreement") is entered into on [DATE], between TechCorp Inc. ("Disclosing Party") and ABC Consulting LLC ("Receiving Party").

1. DEFINITION OF CONFIDENTIAL INFORMATION
"Confidential Information" means any and all non-public, proprietary, or confidential information disclosed by the Disclosing Party.

2. OBLIGATIONS OF RECEIVING PARTY
Receiving Party agrees to:
a) Hold all Confidential Information in strict confidence
b) Not disclose Confidential Information to any third parties
c) Use Confidential Information solely for the purpose of evaluating potential business relationships

3. TERM
This Agreement shall remain in effect for a period of three (3) years from the date of execution.

4. RETURN OF MATERIALS
Upon termination, Receiving Party shall return or destroy all materials containing Confidential Information.

5. REMEDIES
Receiving Party acknowledges that breach of this Agreement may cause irreparable harm, and Disclosing Party shall be entitled to seek injunctive relief.

6. GOVERNING LAW
This Agreement shall be governed by the laws of the State of California.

IN WITNESS WHEREOF, the parties have executed this Agreement.

DISCLOSING PARTY:                  RECEIVING PARTY:
TechCorp Inc.                      ABC Consulting LLC

By: _________________             By: _________________
Name: [Name]                       Name: [Name]
Title: [Title]                     Title: [Title]

LEGAL DISCLAIMER: This document is generated by AI and should be reviewed by a qualified attorney before use. This does not constitute legal advice.',
NOW() - INTERVAL ''1 day''),

(2, 'Service Contract', 'Web Development Services - Digital Agency & Client Corp', 
'SERVICE AGREEMENT

This Service Agreement ("Agreement") is entered into between Digital Creative Agency LLC ("Service Provider") and Client Corp ("Client").

1. SERVICES
Service Provider agrees to provide web development services including:
- Custom website design and development
- Content management system implementation
- Mobile responsive design
- Basic SEO optimization

2. TIMELINE
Project shall commence on [START DATE] and be completed within 8 weeks.

3. COMPENSATION
Total project fee: $25,000
Payment schedule:
- 50% upon signing this agreement
- 25% upon design approval
- 25% upon project completion

4. INTELLECTUAL PROPERTY
Upon full payment, Client shall own all rights to the completed website and custom code.

5. WARRANTIES
Service Provider warrants that all work will be performed in a professional manner and will be free from defects for 90 days.

6. LIMITATION OF LIABILITY
Service Provider''s liability shall not exceed the total amount paid under this Agreement.

7. GOVERNING LAW
This Agreement shall be governed by the laws of the State of New York.

IN WITNESS WHEREOF, the parties have executed this Agreement.

SERVICE PROVIDER:                  CLIENT:
Digital Creative Agency LLC        Client Corp

By: _________________             By: _________________

LEGAL DISCLAIMER: This document is generated by AI and should be reviewed by a qualified attorney before use. This does not constitute legal advice.',
NOW() - INTERVAL ''3 hours''),

(3, 'Independent Contractor', 'Marketing Consultant Agreement - StartupCo & Jane Doe', 
'INDEPENDENT CONTRACTOR AGREEMENT

This Agreement is entered into between StartupCo Inc. ("Company") and Jane Doe ("Contractor").

1. SERVICES
Contractor shall provide marketing consulting services including:
- Marketing strategy development
- Social media campaign management
- Content creation and marketing
- Performance analytics and reporting

2. TERM
This Agreement shall be effective from [START DATE] through [END DATE], unless terminated earlier.

3. COMPENSATION
Contractor shall be paid $5,000 per month, payable on the 1st of each month.

4. INDEPENDENT CONTRACTOR STATUS
Contractor is an independent contractor and not an employee of Company.

5. EXPENSES
Contractor shall be responsible for all expenses unless pre-approved by Company.

6. CONFIDENTIALITY
Contractor agrees to maintain confidentiality of all Company proprietary information.

7. TERMINATION
Either party may terminate this Agreement with 30 days written notice.

8. GOVERNING LAW
This Agreement shall be governed by the laws of the State of Texas.

IN WITNESS WHEREOF, the parties have executed this Agreement.

COMPANY:                          CONTRACTOR:
StartupCo Inc.                    Jane Doe

By: _________________            _________________
Name: [Name]                      Jane Doe
Title: [Title]

LEGAL DISCLAIMER: This document is generated by AI and should be reviewed by a qualified attorney before use. This does not constitute legal advice.',
NOW() - INTERVAL ''5 hours'');

-- Note: The password hashes above are placeholders. In a real application, these would be actual bcrypt hashes.
-- For demo purposes, you can use the password "DemoPassword123!" for all demo accounts.

