const bcrypt = require('bcryptjs');
const { Pool } = require('pg');
require('dotenv').config();

// Demo setup script for VibeLegal
async function setupDemo() {
  console.debug('🚀 Setting up VibeLegal demo data...');
  
  // Create a simple in-memory database simulation for demo
  const demoUsers = [
    {
      email: 'demo@vibelegal.com',
      password: 'DemoPassword123!',
      subscription_tier: 'basic',
      contracts_used_this_month: 3
    },
    {
      email: 'premium@vibelegal.com', 
      password: 'DemoPassword123!',
      subscription_tier: 'premium',
      contracts_used_this_month: 15
    },
    {
      email: 'lawyer@lawfirm.com',
      password: 'DemoPassword123!',
      subscription_tier: 'basic',
      contracts_used_this_month: 8
    }
  ];

  const demoContracts = [
    {
      user_id: 1,
      contract_type: 'Employment Agreement',
      title: 'Software Developer Employment - TechCorp & John Smith',
      content: `EMPLOYMENT AGREEMENT

This Employment Agreement ("Agreement") is entered into on January 15, 2024, between TechCorp Inc., a Delaware corporation ("Company"), and John Smith ("Employee").

1. POSITION AND DUTIES
Employee shall serve as Software Developer and shall perform such duties as are customarily associated with such position, including but not limited to:
- Developing and maintaining web applications
- Collaborating with cross-functional teams
- Writing clean, maintainable code
- Participating in code reviews and technical discussions

2. COMPENSATION
Employee shall receive an annual salary of $85,000, payable in accordance with Company's standard payroll practices (bi-weekly).

3. BENEFITS
Employee shall be entitled to participate in all benefit programs generally available to Company employees, including:
- Health insurance (Company pays 80% of premiums)
- 401(k) retirement plan with company matching
- 15 days paid vacation annually
- 10 days sick leave annually

4. PROBATIONARY PERIOD
Employee's employment shall be subject to a ninety (90) day probationary period during which either party may terminate employment with one week's notice.

5. TERM
This Agreement shall commence on February 1, 2024, and shall continue until terminated in accordance with the provisions herein.

6. TERMINATION
After the probationary period, either party may terminate this Agreement with two (2) weeks written notice.

7. CONFIDENTIALITY
Employee agrees to maintain the confidentiality of all proprietary information of the Company and shall not disclose such information to any third party.

8. NON-COMPETE
Employee agrees not to engage in any competing business activities during employment and for six (6) months after termination.

9. GOVERNING LAW
This Agreement shall be governed by the laws of the State of California.

IN WITNESS WHEREOF, the parties have executed this Agreement as of the date first written above.

COMPANY:                           EMPLOYEE:
TechCorp Inc.                      John Smith

By: _________________             _________________
Name: Sarah Johnson               John Smith
Title: Chief Executive Officer

LEGAL DISCLAIMER: This document is generated by AI and should be reviewed by a qualified attorney before use. This does not constitute legal advice.`
    },
    {
      user_id: 1,
      contract_type: 'NDA',
      title: 'Non-Disclosure Agreement - TechCorp & Consulting Firm',
      content: `NON-DISCLOSURE AGREEMENT

This Non-Disclosure Agreement ("Agreement") is entered into on January 10, 2024, between TechCorp Inc. ("Disclosing Party") and ABC Consulting LLC ("Receiving Party").

RECITALS
WHEREAS, Disclosing Party possesses certain confidential and proprietary information;
WHEREAS, Receiving Party desires to receive such information for the purpose of evaluating potential business opportunities;

NOW, THEREFORE, the parties agree as follows:

1. DEFINITION OF CONFIDENTIAL INFORMATION
"Confidential Information" means any and all non-public, proprietary, or confidential information disclosed by the Disclosing Party, including but not limited to:
- Technical data and specifications
- Business plans and strategies  
- Financial information
- Customer lists and data
- Software code and algorithms

2. OBLIGATIONS OF RECEIVING PARTY
Receiving Party agrees to:
a) Hold all Confidential Information in strict confidence
b) Not disclose Confidential Information to any third parties without prior written consent
c) Use Confidential Information solely for the purpose of evaluating potential business relationships
d) Limit access to Confidential Information to employees with a legitimate need to know

3. EXCEPTIONS
This Agreement shall not apply to information that:
a) Is or becomes publicly available through no breach of this Agreement
b) Was known to Receiving Party prior to disclosure
c) Is independently developed without use of Confidential Information

4. TERM
This Agreement shall remain in effect for a period of three (3) years from the date of execution.

5. RETURN OF MATERIALS
Upon termination of this Agreement, Receiving Party shall promptly return or destroy all materials containing Confidential Information.

6. REMEDIES
Receiving Party acknowledges that breach of this Agreement may cause irreparable harm, and Disclosing Party shall be entitled to seek injunctive relief in addition to other available remedies.

7. GOVERNING LAW
This Agreement shall be governed by the laws of the State of California.

IN WITNESS WHEREOF, the parties have executed this Agreement.

DISCLOSING PARTY:                  RECEIVING PARTY:
TechCorp Inc.                      ABC Consulting LLC

By: _________________             By: _________________
Name: Sarah Johnson               Name: Michael Brown
Title: CEO                        Title: Managing Partner

LEGAL DISCLAIMER: This document is generated by AI and should be reviewed by a qualified attorney before use. This does not constitute legal advice.`
    }
  ];

  // Hash passwords for demo users
  for (let user of demoUsers) {
    user.password_hash = await bcrypt.hash(user.password, 10);
    delete user.password;
  }

  console.debug('✅ Demo data prepared successfully!');
  console.debug('\n📋 Demo Accounts:');
  console.debug('1. demo@vibelegal.com (Password: DemoPassword123!)');
  console.debug('2. premium@vibelegal.com (Password: DemoPassword123!)');
  console.debug('3. lawyer@lawfirm.com (Password: DemoPassword123!)');
  
  console.debug('\n🎯 Demo Features:');
  console.debug('- User registration and authentication');
  console.debug('- Contract generation with AI (requires OpenAI API key)');
  console.debug('- Contract saving and management');
  console.debug('- Responsive design for mobile and desktop');
  console.debug('- Professional UI with Tailwind CSS');
  
  return { demoUsers, demoContracts };
}

// Export for use in other scripts
module.exports = { setupDemo };

// Run if called directly
if (require.main === module) {
  setupDemo().catch(console.error);
}

