#!/usr/bin/env node

/**
 * Stripe Setup Script
 * 
 * This script helps set up Stripe products and pricing for VibeLegal.
 * Run this after setting up your Stripe account to automatically create
 * the necessary products and price IDs.
 * 
 * Usage:
 *   1. Set your STRIPE_SECRET_KEY in .env file
 *   2. Run: node setup-stripe.js
 *   3. Copy the generated price IDs to your .env file
 */

require('dotenv').config();
const stripe = require('stripe')(process.env.STRIPE_SECRET_KEY);

const products = [
  {
    name: 'VibeLegal Pro',
    description: 'AI-powered contract generation with conversational interface and advanced customization',
    prices: [
      {
        nickname: 'Pro Monthly',
        unit_amount: 2900, // $29.00 in cents
        currency: 'usd',
        recurring: { interval: 'month' },
        env_key: 'STRIPE_PRO_MONTHLY_PRICE_ID'
      },
      {
        nickname: 'Pro Yearly',
        unit_amount: 29000, // $290.00 in cents (17% discount)
        currency: 'usd',
        recurring: { interval: 'year' },
        env_key: 'STRIPE_PRO_YEARLY_PRICE_ID'
      }
    ]
  },
  {
    name: 'VibeLegal Enterprise',
    description: 'Everything in Pro plus team collaboration, analytics, and dedicated support',
    prices: [
      {
        nickname: 'Enterprise Monthly',
        unit_amount: 9900, // $99.00 in cents
        currency: 'usd',
        recurring: { interval: 'month' },
        env_key: 'STRIPE_ENTERPRISE_MONTHLY_PRICE_ID'
      },
      {
        nickname: 'Enterprise Yearly',
        unit_amount: 99000, // $990.00 in cents (17% discount)
        currency: 'usd',
        recurring: { interval: 'year' },
        env_key: 'STRIPE_ENTERPRISE_YEARLY_PRICE_ID'
      }
    ]
  }
];

async function setupStripeProducts() {
  console.log('🚀 Setting up Stripe products and pricing for VibeLegal...\n');

  if (!process.env.STRIPE_SECRET_KEY) {
    console.error('❌ Error: STRIPE_SECRET_KEY not found in environment variables');
    console.error('Please add your Stripe secret key to the .env file');
    process.exit(1);
  }

  const createdPrices = [];

  try {
    for (const productData of products) {
      console.log(`📦 Creating product: ${productData.name}`);
      
      // Create product
      const product = await stripe.products.create({
        name: productData.name,
        description: productData.description,
        metadata: {
          created_by: 'vibelegal-setup-script',
          product_type: productData.name.toLowerCase().includes('pro') ? 'pro' : 'enterprise'
        }
      });

      console.log(`✅ Product created: ${product.id}\n`);

      // Create prices for this product
      for (const priceData of productData.prices) {
        console.log(`  💰 Creating price: ${priceData.nickname}`);
        
        const price = await stripe.prices.create({
          product: product.id,
          nickname: priceData.nickname,
          unit_amount: priceData.unit_amount,
          currency: priceData.currency,
          recurring: priceData.recurring,
          metadata: {
            created_by: 'vibelegal-setup-script',
            tier: productData.name.toLowerCase().includes('pro') ? 'pro' : 'enterprise',
            billing_cycle: priceData.recurring.interval
          }
        });

        console.log(`  ✅ Price created: ${price.id}`);
        
        createdPrices.push({
          env_key: priceData.env_key,
          price_id: price.id,
          nickname: priceData.nickname,
          amount: priceData.unit_amount / 100,
          interval: priceData.recurring.interval
        });
      }
      console.log('');
    }

    console.log('🎉 All products and prices created successfully!\n');
    console.log('📋 Add these price IDs to your .env file:\n');
    console.log('# Stripe Price IDs (generated by setup-stripe.js)');
    
    createdPrices.forEach(price => {
      console.log(`${price.env_key}=${price.price_id}`);
    });

    console.log('\n💡 Next steps:');
    console.log('1. Copy the price IDs above to your .env file');
    console.log('2. Set up webhook endpoints in your Stripe Dashboard');
    console.log('3. Add the webhook secret to your .env file');
    console.log('4. Test the payment flow in your application\n');

    console.log('🔗 Useful Stripe Dashboard links:');
    console.log('- Products: https://dashboard.stripe.com/test/products');
    console.log('- Webhooks: https://dashboard.stripe.com/test/webhooks');
    console.log('- API Keys: https://dashboard.stripe.com/test/apikeys');

  } catch (error) {
    console.error('❌ Error setting up Stripe products:', error.message);
    
    if (error.type === 'StripeAuthenticationError') {
      console.error('\n💡 This looks like an authentication error.');
      console.error('Please check that your STRIPE_SECRET_KEY is correct and starts with "sk_"');
    }
    
    process.exit(1);
  }
}

// Check if this script is being run directly
if (require.main === module) {
  setupStripeProducts();
}

module.exports = { setupStripeProducts };