import React, { useState, useEffect, useContext } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import { AuthContext } from '../App';
import config from '../config.js';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { 
  ArrowLeft, 
  FileText, 
  Download,
  Calendar,
  User,
  Building,
  AlertCircle,
  Printer,
  ChevronDown
} from 'lucide-react';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';

const ContractViewer = () => {
  const { id } = useParams();
  const { user, handleAuthError } = useContext(AuthContext);
  const navigate = useNavigate();
  const [contract, setContract] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    fetchContract();
  }, [id]);

  const fetchContract = async () => {
    try {
      const token = localStorage.getItem('token');
      const response = await fetch(`${config.API_BASE_URL}/api/contracts/${id}`, {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });

      const data = await response.json();

      if (response.ok) {
        setContract(data.contract);
      } else {
        if (response.status === 401 || response.status === 403) {
          handleAuthError();
          return;
        }
        setError(data.error || 'Failed to fetch contract');
      }
    } catch (err) {
      setError('Network error. Please try again.');
      console.error('Contract fetch error:', err);
    } finally {
      setLoading(false);
    }
  };

  const createDisclaimer = () => {
    return `
⚠️ IMPORTANT LEGAL DISCLAIMER ⚠️

This contract was generated using AI technology and is provided for informational purposes only.

ALWAYS have contracts reviewed by qualified California employment law attorneys before use.

VibeLegal does not provide legal advice and should not be considered a substitute for professional legal counsel. By using this service, you acknowledge that professional legal review is essential before executing any contract.

🚨 DO NOT USE THIS CONTRACT WITHOUT ATTORNEY REVIEW 🚨

Generated by VibeLegal (Beta) - https://vibelegal.com
Generated on: ${new Date().toLocaleString()}

════════════════════════════════════════════════════════════════════════════════

CONTRACT CONTENT BEGINS BELOW:

`;
  };

  const downloadContract = (format = 'txt') => {
    if (!contract) return;
    
    const disclaimer = createDisclaimer();
    const fullContent = disclaimer + contract.content;
    const fileName = contract.title.replace(/[^a-z0-9]/gi, '_');
    
    let blob, mimeType, fileExtension;
    
    switch (format) {
      case 'html':
        const htmlContent = `
<!DOCTYPE html>
<html>
<head>
    <title>${contract.title}</title>
    <style>
        body { font-family: 'Times New Roman', serif; max-width: 8.5in; margin: 0 auto; padding: 1in; line-height: 1.6; }
        .disclaimer { background: #ffe6e6; border: 2px solid #ff0000; padding: 20px; margin-bottom: 30px; color: #cc0000; }
        .disclaimer h1 { color: #cc0000; text-align: center; margin-top: 0; }
        .contract-content { font-size: 12pt; white-space: pre-wrap; }
        @media print {
          .disclaimer { page-break-after: always; }
        }
    </style>
</head>
<body>
    <div class="disclaimer">
        <h1>⚠️ IMPORTANT LEGAL DISCLAIMER ⚠️</h1>
        <p><strong>This contract was generated using AI technology and is provided for informational purposes only.</strong></p>
        <p><strong>ALWAYS have contracts reviewed by qualified California employment law attorneys before use.</strong></p>
        <p>VibeLegal does not provide legal advice and should not be considered a substitute for professional legal counsel.</p>
        <p style="text-align: center; font-weight: bold; background: #ffcccc; padding: 10px; border-radius: 5px;">
            🚨 DO NOT USE THIS CONTRACT WITHOUT ATTORNEY REVIEW 🚨
        </p>
        <p><em>Generated by VibeLegal (Beta) on ${new Date().toLocaleString()}</em></p>
    </div>
    <div class="contract-content">${contract.content}</div>
</body>
</html>`;
        blob = new Blob([htmlContent], { type: 'text/html' });
        mimeType = 'text/html';
        fileExtension = 'html';
        break;
        
      case 'pdf':
        // For now, create a rich text version that can be easily converted to PDF
        blob = new Blob([fullContent], { type: 'text/plain' });
        mimeType = 'text/plain';
        fileExtension = 'txt';
        // TODO: Implement proper PDF generation
        alert('PDF generation coming soon! For now, use HTML format and print to PDF from your browser.');
        return;
        
      case 'doc':
        // Create a basic RTF format that opens in Word
        const rtfContent = `{\\rtf1\\ansi\\deff0 {\\fonttbl {\\f0 Times New Roman;}}
\\f0\\fs24 ${fullContent.replace(/\n/g, '\\par ')}}`;
        blob = new Blob([rtfContent], { type: 'application/rtf' });
        mimeType = 'application/rtf';
        fileExtension = 'rtf';
        break;
        
      default: // txt
        blob = new Blob([fullContent], { type: 'text/plain' });
        mimeType = 'text/plain';
        fileExtension = 'txt';
    }
    
    const element = document.createElement('a');
    element.href = URL.createObjectURL(blob);
    element.download = `${fileName}.${fileExtension}`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const printContract = () => {
    const disclaimer = createDisclaimer();
    const printWindow = window.open('', '', 'height=600,width=800');
    printWindow.document.write(`
      <html>
        <head>
          <title>${contract.title}</title>
          <style>
            body { font-family: 'Times New Roman', serif; line-height: 1.6; margin: 0.5in; }
            .disclaimer { background: #ffe6e6; border: 2px solid #ff0000; padding: 15px; margin-bottom: 20px; color: #cc0000; page-break-after: always; }
            .disclaimer h1 { color: #cc0000; text-align: center; margin-top: 0; }
            .contract-content { white-space: pre-wrap; font-size: 12pt; }
          </style>
        </head>
        <body>
          <div class="disclaimer">
            <h1>⚠️ IMPORTANT LEGAL DISCLAIMER ⚠️</h1>
            <p><strong>This contract was generated using AI technology and is provided for informational purposes only.</strong></p>
            <p><strong>ALWAYS have contracts reviewed by qualified California employment law attorneys before use.</strong></p>
            <p>🚨 DO NOT USE THIS CONTRACT WITHOUT ATTORNEY REVIEW 🚨</p>
          </div>
          <div class="contract-content">${contract.content}</div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const getContractTypeColor = (type) => {
    const colors = {
      'Employment Agreement': 'bg-gray-100 text-gray-800', // Basic → Grey
      'CA Employment Agreement': 'bg-gray-100 text-gray-800', // Basic → Grey
      'Enhanced Employment Agreement': 'bg-blue-100 text-blue-800', // Enhanced → Blue
      'Conversational AI Employment Agreement': 'bg-purple-100 text-purple-800' // AI Chat → Purple
    };
    return colors[type] || 'bg-gray-100 text-gray-800';
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 py-8">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-center py-16">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50 py-8">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="mb-6">
            <Button variant="ghost" onClick={() => navigate('/dashboard')}>
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Dashboard
            </Button>
          </div>
          
          <Card className="border-red-200 bg-red-50">
            <CardContent className="p-6">
              <div className="flex items-center space-x-3">
                <AlertCircle className="h-8 w-8 text-red-600" />
                <div>
                  <h3 className="text-lg font-semibold text-red-800">Error Loading Contract</h3>
                  <p className="text-red-700">{error}</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  if (!contract) {
    return (
      <div className="min-h-screen bg-gray-50 py-8">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="mb-6">
            <Button variant="ghost" onClick={() => navigate('/dashboard')}>
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Dashboard
            </Button>
          </div>
          
          <Card>
            <CardContent className="p-6 text-center">
              <FileText className="h-12 w-12 text-gray-400 mx-auto mb-4" />
              <h3 className="text-lg font-medium text-gray-900 mb-2">Contract Not Found</h3>
              <p className="text-gray-600">The requested contract could not be found.</p>
            </CardContent>
          </Card>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-6">
          <Button variant="ghost" onClick={() => navigate('/dashboard')}>
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Dashboard
          </Button>
        </div>

        {/* PROMINENT Legal Disclaimer - TOP of page */}
        <div className="mb-6">
          <Card className="bg-red-50 border-red-300 border-2">
            <CardContent className="p-6">
              <div className="flex items-start">
                <AlertCircle className="h-6 w-6 text-red-600 mt-0.5 mr-4 flex-shrink-0" />
                <div>
                  <h3 className="text-lg font-bold text-red-900 mb-3">⚠️ IMPORTANT LEGAL DISCLAIMER</h3>
                  <div className="text-red-800 space-y-2">
                    <p className="font-semibold">
                      This contract was generated using AI technology and is provided for informational purposes only.
                    </p>
                    <p className="font-semibold">
                      <strong>ALWAYS have contracts reviewed by qualified California employment law attorneys before use.</strong>
                    </p>
                    <p>
                      VibeLegal does not provide legal advice and should not be considered a substitute for professional legal counsel. 
                      By using this service, you acknowledge that professional legal review is essential before executing any contract.
                    </p>
                    <p className="text-sm font-medium bg-red-100 p-2 rounded">
                      🚨 DO NOT USE THIS CONTRACT WITHOUT ATTORNEY REVIEW 🚨
                    </p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Contract Header */}
        <Card className="mb-6">
          <CardHeader>
            <div className="flex items-start justify-between">
              <div className="flex-1">
                <CardTitle className="text-2xl font-bold text-gray-900 mb-2">
                  {contract.title}
                </CardTitle>
                <div className="flex items-center space-x-4 mb-4">
                  <Badge 
                    variant="secondary" 
                    className={getContractTypeColor(contract.contract_type)}
                  >
                    {contract.contract_type}
                  </Badge>
                  <div className="flex items-center text-sm text-gray-600">
                    <Calendar className="h-4 w-4 mr-1" />
                    Created {formatDate(contract.created_at)}
                  </div>
                </div>
                <CardDescription className="text-base">
                  View and download your generated contract. Always have contracts reviewed by qualified legal counsel before use.
                </CardDescription>
              </div>
              <div className="flex space-x-3">
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button className="flex items-center">
                      <Download className="mr-2 h-4 w-4" />
                      Download
                      <ChevronDown className="ml-1 h-4 w-4" />
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent>
                    <DropdownMenuItem onClick={() => downloadContract('html')}>
                      <FileText className="mr-2 h-4 w-4" />
                      HTML (with disclaimer page)
                    </DropdownMenuItem>
                    <DropdownMenuItem onClick={() => downloadContract('doc')}>
                      <FileText className="mr-2 h-4 w-4" />
                      Word Document (.rtf)
                    </DropdownMenuItem>
                    <DropdownMenuItem onClick={() => downloadContract('txt')}>
                      <FileText className="mr-2 h-4 w-4" />
                      Text File (.txt)
                    </DropdownMenuItem>
                    <DropdownMenuItem onClick={() => downloadContract('pdf')}>
                      <FileText className="mr-2 h-4 w-4" />
                      PDF (coming soon)
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>
                
                <Button onClick={printContract} variant="outline" className="flex items-center">
                  <Printer className="mr-2 h-4 w-4" />
                  Print
                </Button>
              </div>
            </div>
          </CardHeader>
        </Card>

        {/* Contract Content */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center">
              <FileText className="mr-2 h-5 w-5" />
              Contract Content
            </CardTitle>
            <CardDescription>
              Full contract text as generated
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="bg-white border rounded-lg p-6 font-mono text-sm leading-relaxed whitespace-pre-wrap max-h-96 overflow-y-auto">
              {contract.content}
            </div>
            
          </CardContent>
        </Card>

        {/* Legal Disclaimer - Moved to bottom */}
        <div className="mt-6">
          <Card className="bg-blue-50 border-blue-200">
            <CardContent className="p-6">
              <div className="flex items-start">
                <AlertCircle className="h-5 w-5 text-blue-600 mt-0.5 mr-3 flex-shrink-0" />
                <div>
                  <h4 className="text-sm font-semibold text-blue-900 mb-2">Legal Disclaimer</h4>
                  <p className="text-sm text-blue-800 leading-relaxed">
                    This contract was generated using AI technology and is provided for informational purposes only. 
                    <strong> Always have contracts reviewed by qualified California employment law attorneys before use.</strong> VibeLegal 
                    does not provide legal advice and should not be considered a substitute for professional legal counsel. 
                    By using this service, you acknowledge that legal review is essential before executing any contract.
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default ContractViewer;