import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Switch } from '@/components/ui/switch';
import { Slider } from '@/components/ui/slider';
import { Badge } from '@/components/ui/badge';
import { 
  Type, 
  Palette, 
  Download, 
  FileText, 
  Settings, 
  Eye,
  Image,
  Layout,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Bold,
  Italic,
  Underline,
  Wand2
} from 'lucide-react';

// Font options for professional documents
const FONT_OPTIONS = [
  { value: 'Times New Roman', label: 'Times New Roman (Traditional Legal)' },
  { value: 'Arial', label: 'Arial (Modern, Clean)' },
  { value: 'Calibri', label: 'Calibri (Professional)' },
  { value: 'Georgia', label: 'Georgia (Elegant Serif)' },
  { value: 'Helvetica', label: 'Helvetica (Clean Sans-serif)' },
  { value: 'Garamond', label: 'Garamond (Classic Legal)' }
];

// Color schemes for professional documents
const COLOR_SCHEMES = [
  { name: 'Traditional Black', primary: '#000000', secondary: '#333333', background: '#ffffff' },
  { name: 'Professional Navy', primary: '#1e3a8a', secondary: '#3730a3', background: '#f8fafc' },
  { name: 'Corporate Blue', primary: '#1e40af', secondary: '#2563eb', background: '#f1f5f9' },
  { name: 'Legal Gray', primary: '#374151', secondary: '#6b7280', background: '#f9fafb' },
  { name: 'Executive Green', primary: '#166534', secondary: '#16a34a', background: '#f0fdf4' }
];

// Watermark options
const WATERMARK_OPTIONS = [
  { value: 'draft', label: 'DRAFT', opacity: 0.1 },
  { value: 'confidential', label: 'CONFIDENTIAL', opacity: 0.15 },
  { value: 'internal', label: 'INTERNAL USE', opacity: 0.1 },
  { value: 'review', label: 'FOR REVIEW', opacity: 0.1 },
  { value: 'sample', label: 'SAMPLE', opacity: 0.12 },
  { value: 'custom', label: 'Custom Text', opacity: 0.1 }
];

export function ContractEditor({ 
  contractContent, 
  contractTitle, 
  onContentChange, 
  onTitleChange,
  onDownload 
}) {
  // Formatting state
  const [fontFamily, setFontFamily] = useState('Times New Roman');
  const [fontSize, setFontSize] = useState([12]);
  const [lineHeight, setLineHeight] = useState([1.6]);
  const [colorScheme, setColorScheme] = useState(COLOR_SCHEMES[0]);
  const [textAlignment, setTextAlignment] = useState('left');
  
  // Text formatting states
  const [isBold, setIsBold] = useState(false);
  const [isItalic, setIsItalic] = useState(false);
  const [isUnderline, setIsUnderline] = useState(false);
  
  // Watermark settings
  const [watermarkEnabled, setWatermarkEnabled] = useState(false);
  const [watermarkType, setWatermarkType] = useState('draft');
  const [customWatermarkText, setCustomWatermarkText] = useState('');
  const [watermarkOpacity, setWatermarkOpacity] = useState([0.1]);
  
  // Page settings
  const [pageMargins, setPageMargins] = useState([1.0]);
  const [includeHeader, setIncludeHeader] = useState(true);
  const [includeFooter, setIncludeFooter] = useState(true);
  const [headerText, setHeaderText] = useState(contractTitle);
  const [footerText, setFooterText] = useState('Generated by VibeLegal.com');
  
  // Preview mode
  const [previewMode, setPreviewMode] = useState(false);

  const getWatermarkText = () => {
    if (watermarkType === 'custom') {
      return customWatermarkText || 'DRAFT';
    }
    return WATERMARK_OPTIONS.find(opt => opt.value === watermarkType)?.label || 'DRAFT';
  };

  const generateStyledHTML = () => {
    const watermarkHTML = watermarkEnabled ? `
      <div class="watermark" style="
        position: fixed;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%) rotate(-45deg);
        font-size: 72px;
        font-weight: bold;
        color: ${colorScheme.primary};
        opacity: ${watermarkOpacity[0]};
        z-index: 0;
        pointer-events: none;
        user-select: none;
        white-space: nowrap;
      ">
        ${getWatermarkText()}
      </div>
    ` : '';

    const headerHTML = includeHeader ? `
      <div class="page-header" style="
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        height: 60px;
        background: ${colorScheme.background};
        border-bottom: 1px solid ${colorScheme.secondary};
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 14px;
        color: ${colorScheme.secondary};
        z-index: 10;
      ">
        ${headerText}
      </div>
    ` : '';

    const footerHTML = includeFooter ? `
      <div class="page-footer" style="
        position: fixed;
        bottom: 0;
        left: 0;
        right: 0;
        height: 40px;
        background: ${colorScheme.background};
        border-top: 1px solid ${colorScheme.secondary};
        display: flex;
        align-items: center;
        justify-content: center;
        font-size: 12px;
        color: ${colorScheme.secondary};
        z-index: 10;
      ">
        ${footerText} | Page <span class="page-number"></span>
      </div>
    ` : '';

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${contractTitle}</title>
        <style>
          @page {
            margin: ${pageMargins[0]}in;
            size: letter;
          }
          
          body {
            font-family: ${fontFamily}, serif;
            font-size: ${fontSize[0]}pt;
            line-height: ${lineHeight[0]};
            color: ${colorScheme.primary};
            background-color: ${colorScheme.background};
            margin: 0;
            padding: ${includeHeader ? '80px' : '20px'} 20px ${includeFooter ? '60px' : '20px'} 20px;
            position: relative;
            ${isBold ? 'font-weight: bold;' : ''}
            ${isItalic ? 'font-style: italic;' : ''}
            ${isUnderline ? 'text-decoration: underline;' : ''}
          }
          
          .contract-content {
            text-align: ${textAlignment};
            white-space: pre-wrap;
            position: relative;
            z-index: 1;
          }
          
          .contract-title {
            font-size: ${fontSize[0] * 1.5}pt;
            font-weight: bold;
            text-align: center;
            margin-bottom: 30px;
            color: ${colorScheme.primary};
            border-bottom: 2px solid ${colorScheme.primary};
            padding-bottom: 15px;
          }
          
          h1, h2, h3 {
            color: ${colorScheme.primary};
            font-weight: bold;
          }
          
          .page-break {
            page-break-before: always;
          }
          
          @media print {
            .page-header, .page-footer {
              position: fixed;
            }
            
            .page-footer .page-number:after {
              content: counter(page);
            }
          }
        </style>
      </head>
      <body>
        ${watermarkHTML}
        ${headerHTML}
        ${footerHTML}
        
        <div class="contract-title">${contractTitle}</div>
        <div class="contract-content">${contractContent.replace(/\n/g, '<br>')}</div>
        
        <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid ${colorScheme.secondary}; font-size: 10pt; color: ${colorScheme.secondary}; text-align: center;">
          <p><strong>IMPORTANT LEGAL DISCLAIMER</strong></p>
          <p>This document was generated by AI and should be reviewed by a qualified attorney before use. This does not constitute legal advice. VibeLegal.com provides document generation tools only and is not responsible for the legal accuracy or enforceability of generated documents.</p>
          <p>Generated on ${new Date().toLocaleDateString()} via VibeLegal.com</p>
        </div>
      </body>
      </html>
    `;
  };

  const handleDownloadStyled = (format = 'html') => {
    const styledHTML = generateStyledHTML();
    
    if (format === 'html') {
      const blob = new Blob([styledHTML], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${contractTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_styled.html`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } else if (format === 'word') {
      // Create Word-compatible HTML
      const wordHTML = `
        <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
        <head><meta charset='utf-8'><title>${contractTitle}</title></head>
        <body>${styledHTML.replace(/<style>[\s\S]*?<\/style>/, '')}</body>
        </html>
      `;
      const blob = new Blob([wordHTML], { type: 'application/msword' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${contractTitle.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.doc`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }
    
    if (onDownload) {
      onDownload(format);
    }
  };

  const contractStyles = {
    fontFamily: fontFamily,
    fontSize: `${fontSize[0]}pt`,
    lineHeight: lineHeight[0],
    color: colorScheme.primary,
    backgroundColor: colorScheme.background,
    textAlign: textAlignment,
    fontWeight: isBold ? 'bold' : 'normal',
    fontStyle: isItalic ? 'italic' : 'normal',
    textDecoration: isUnderline ? 'underline' : 'none',
    position: 'relative'
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Settings className="w-5 h-5 text-purple-600" />
            Professional Contract Editor
            <Badge variant="secondary">Pro Feature</Badge>
          </CardTitle>
          <CardDescription>
            Customize fonts, formatting, watermarks, and styling for professional contract documents
          </CardDescription>
        </CardHeader>
        
        <CardContent>
          <Tabs defaultValue="formatting" className="w-full">
            <TabsList className="grid w-full grid-cols-4">
              <TabsTrigger value="formatting">
                <Type className="w-4 h-4 mr-2" />
                Typography
              </TabsTrigger>
              <TabsTrigger value="styling">
                <Palette className="w-4 h-4 mr-2" />
                Styling
              </TabsTrigger>
              <TabsTrigger value="watermark">
                <Image className="w-4 h-4 mr-2" />
                Watermark
              </TabsTrigger>
              <TabsTrigger value="layout">
                <Layout className="w-4 h-4 mr-2" />
                Layout
              </TabsTrigger>
            </TabsList>

            <TabsContent value="formatting" className="space-y-6 mt-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                  <Label className="text-sm font-medium">Font Family</Label>
                  <Select value={fontFamily} onValueChange={setFontFamily}>
                    <SelectTrigger className="mt-1">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {FONT_OPTIONS.map((font) => (
                        <SelectItem key={font.value} value={font.value}>
                          {font.label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                
                <div>
                  <Label className="text-sm font-medium">Font Size: {fontSize[0]}pt</Label>
                  <Slider
                    value={fontSize}
                    onValueChange={setFontSize}
                    min={8}
                    max={16}
                    step={1}
                    className="mt-2"
                  />
                </div>
                
                <div>
                  <Label className="text-sm font-medium">Line Height: {lineHeight[0]}</Label>
                  <Slider
                    value={lineHeight}
                    onValueChange={setLineHeight}
                    min={1.0}
                    max={2.5}
                    step={0.1}
                    className="mt-2"
                  />
                </div>
                
                <div>
                  <Label className="text-sm font-medium">Text Alignment</Label>
                  <div className="flex gap-2 mt-2">
                    <Button
                      variant={textAlignment === 'left' ? 'default' : 'outline'}
                      size="sm"
                      onClick={() => setTextAlignment('left')}
                    >
                      <AlignLeft className="w-4 h-4" />
                    </Button>
                    <Button
                      variant={textAlignment === 'center' ? 'default' : 'outline'}
                      size="sm"
                      onClick={() => setTextAlignment('center')}
                    >
                      <AlignCenter className="w-4 h-4" />
                    </Button>
                    <Button
                      variant={textAlignment === 'right' ? 'default' : 'outline'}
                      size="sm"
                      onClick={() => setTextAlignment('right')}
                    >
                      <AlignRight className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              </div>
              
              <div>
                <Label className="text-sm font-medium">Text Formatting</Label>
                <div className="flex gap-2 mt-2">
                  <Button
                    variant={isBold ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => setIsBold(!isBold)}
                  >
                    <Bold className="w-4 h-4" />
                  </Button>
                  <Button
                    variant={isItalic ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => setIsItalic(!isItalic)}
                  >
                    <Italic className="w-4 h-4" />
                  </Button>
                  <Button
                    variant={isUnderline ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => setIsUnderline(!isUnderline)}
                  >
                    <Underline className="w-4 h-4" />
                  </Button>
                </div>
              </div>
            </TabsContent>

            <TabsContent value="styling" className="space-y-6 mt-6">
              <div>
                <Label className="text-sm font-medium">Color Scheme</Label>
                <div className="grid grid-cols-1 gap-3 mt-2">
                  {COLOR_SCHEMES.map((scheme, index) => (
                    <div
                      key={index}
                      className={`p-3 rounded-lg border-2 cursor-pointer transition-all ${
                        colorScheme.name === scheme.name 
                          ? 'border-blue-500 bg-blue-50' 
                          : 'border-gray-200 hover:border-gray-300'
                      }`}
                      onClick={() => setColorScheme(scheme)}
                    >
                      <div className="flex items-center justify-between">
                        <span className="font-medium">{scheme.name}</span>
                        <div className="flex gap-2">
                          <div 
                            className="w-4 h-4 rounded" 
                            style={{ backgroundColor: scheme.primary }}
                          />
                          <div 
                            className="w-4 h-4 rounded" 
                            style={{ backgroundColor: scheme.secondary }}
                          />
                          <div 
                            className="w-4 h-4 rounded border" 
                            style={{ backgroundColor: scheme.background }}
                          />
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </TabsContent>

            <TabsContent value="watermark" className="space-y-6 mt-6">
              <div className="flex items-center justify-between">
                <div>
                  <Label className="text-sm font-medium">Enable Watermark</Label>
                  <p className="text-xs text-gray-500 mt-1">Add a watermark to your contract</p>
                </div>
                <Switch
                  checked={watermarkEnabled}
                  onCheckedChange={setWatermarkEnabled}
                />
              </div>
              
              {watermarkEnabled && (
                <div className="space-y-4">
                  <div>
                    <Label className="text-sm font-medium">Watermark Type</Label>
                    <Select value={watermarkType} onValueChange={setWatermarkType}>
                      <SelectTrigger className="mt-1">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        {WATERMARK_OPTIONS.map((option) => (
                          <SelectItem key={option.value} value={option.value}>
                            {option.label}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  
                  {watermarkType === 'custom' && (
                    <div>
                      <Label className="text-sm font-medium">Custom Watermark Text</Label>
                      <Input
                        value={customWatermarkText}
                        onChange={(e) => setCustomWatermarkText(e.target.value)}
                        placeholder="Enter custom watermark text"
                        className="mt-1"
                      />
                    </div>
                  )}
                  
                  <div>
                    <Label className="text-sm font-medium">
                      Opacity: {Math.round(watermarkOpacity[0] * 100)}%
                    </Label>
                    <Slider
                      value={watermarkOpacity}
                      onValueChange={setWatermarkOpacity}
                      min={0.05}
                      max={0.3}
                      step={0.01}
                      className="mt-2"
                    />
                  </div>
                </div>
              )}
            </TabsContent>

            <TabsContent value="layout" className="space-y-6 mt-6">
              <div>
                <Label className="text-sm font-medium">
                  Page Margins: {pageMargins[0]}"
                </Label>
                <Slider
                  value={pageMargins}
                  onValueChange={setPageMargins}
                  min={0.5}
                  max={2.0}
                  step={0.1}
                  className="mt-2"
                />
              </div>
              
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <Label className="text-sm font-medium">Include Header</Label>
                    <p className="text-xs text-gray-500 mt-1">Show header on every page</p>
                  </div>
                  <Switch
                    checked={includeHeader}
                    onCheckedChange={setIncludeHeader}
                  />
                </div>
                
                {includeHeader && (
                  <div>
                    <Label className="text-sm font-medium">Header Text</Label>
                    <Input
                      value={headerText}
                      onChange={(e) => setHeaderText(e.target.value)}
                      className="mt-1"
                    />
                  </div>
                )}
                
                <div className="flex items-center justify-between">
                  <div>
                    <Label className="text-sm font-medium">Include Footer</Label>
                    <p className="text-xs text-gray-500 mt-1">Show footer with page numbers</p>
                  </div>
                  <Switch
                    checked={includeFooter}
                    onCheckedChange={setIncludeFooter}
                  />
                </div>
                
                {includeFooter && (
                  <div>
                    <Label className="text-sm font-medium">Footer Text</Label>
                    <Input
                      value={footerText}
                      onChange={(e) => setFooterText(e.target.value)}
                      className="mt-1"
                    />
                  </div>
                )}
              </div>
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>

      {/* Preview Section */}
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <Eye className="w-5 h-5 text-blue-600" />
                Live Preview
              </CardTitle>
              <CardDescription>
                See how your contract will look with current formatting
              </CardDescription>
            </div>
            <Button
              variant="outline"
              onClick={() => setPreviewMode(!previewMode)}
            >
              {previewMode ? 'Edit Mode' : 'Preview Mode'}
            </Button>
          </div>
        </CardHeader>
        
        <CardContent>
          {previewMode ? (
            <div 
              className="border rounded-lg p-6 min-h-[400px] bg-white"
              style={contractStyles}
            >
              {watermarkEnabled && (
                <div
                  style={{
                    position: 'absolute',
                    top: '50%',
                    left: '50%',
                    transform: 'translate(-50%, -50%) rotate(-45deg)',
                    fontSize: '48px',
                    fontWeight: 'bold',
                    color: colorScheme.primary,
                    opacity: watermarkOpacity[0],
                    zIndex: 0,
                    pointerEvents: 'none',
                    userSelect: 'none',
                    whiteSpace: 'nowrap'
                  }}
                >
                  {getWatermarkText()}
                </div>
              )}
              <div style={{ position: 'relative', zIndex: 1 }}>
                <h1 style={{ fontSize: `${fontSize[0] * 1.5}pt`, marginBottom: '20px', textAlign: 'center' }}>
                  {contractTitle}
                </h1>
                <div style={{ whiteSpace: 'pre-wrap' }}>
                  {contractContent}
                </div>
              </div>
            </div>
          ) : (
            <Textarea
              value={contractContent}
              onChange={(e) => onContentChange(e.target.value)}
              className="min-h-[400px] font-mono text-sm"
              style={contractStyles}
            />
          )}
        </CardContent>
      </Card>

      {/* Download Actions */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Download className="w-5 h-5 text-green-600" />
            Professional Downloads
          </CardTitle>
          <CardDescription>
            Download your contract with professional formatting applied
          </CardDescription>
        </CardHeader>
        
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Button
              onClick={() => handleDownloadStyled('html')}
              className="flex items-center gap-2"
            >
              <FileText className="w-4 h-4" />
              Download Styled HTML
            </Button>
            
            <Button
              onClick={() => handleDownloadStyled('word')}
              variant="outline"
              className="flex items-center gap-2"
            >
              <FileText className="w-4 h-4" />
              Download Word Document
            </Button>
          </div>
          
          <div className="mt-4 p-3 bg-blue-50 rounded-lg border border-blue-200">
            <p className="text-sm text-blue-700">
              <strong>Pro Tip:</strong> The HTML version provides the most accurate formatting and can be opened in any browser or converted to PDF. 
              The Word document is compatible with Microsoft Word and other document editors.
            </p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}