
services:
  server:
    build: ./server
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: unless-stopped

  web:
    build: ./web
    restart: unless-stopped

  proxy:
    image: nginx:alpine
    depends_on:
      - server
      - web
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro,Z
    ports:
      - "8080:80"
    restart: unless-stopped
